"use strict";

const $=id=>document.getElementById(id),colors={ink:"#0b1e2d",deep:"#123b54",steel:"#2c5670",amber:"#d99124",jade:"#3e8e7e",brick:"#b5443a",muted:"#64798a",line:"#d3dbe2"};
const defaults={product:"bonus_outperformance",participation:1.1,bonus:110,barrier:70,monitoring:"daily",finalLevel:95,tenor:2,vol:25,dividend:4,fee:.5};
const presets={outperformance:{participation:1.25},bonus:{participation:1,bonus:115},bonus_outperformance:{participation:1.1,bonus:110}};
const controls=[
  {key:"product",type:"radio",label:"Product",options:[["outperformance","Outperformance · 1310"],["bonus","Bonus · 1320"],["bonus_outperformance","Bonus outperformance · 1330"]]},
  {key:"participation",type:"range",label:"Upside participation",min:1,max:1.8,step:.05,format:v=>(v*100).toFixed(0)+"%",show:p=>p.product!=="bonus"},
  {key:"bonus",type:"range",label:"Bonus level",min:100,max:140,step:1,format:v=>v.toFixed(0),show:p=>p.product!=="outperformance"},
  {key:"barrier",type:"range",label:"Barrier",min:50,max:90,step:1,format:v=>v.toFixed(0),show:p=>p.product!=="outperformance"},
  {key:"monitoring",type:"radio",label:"Barrier monitoring",options:[["daily","Daily closes"],["maturity","Maturity only"]],show:p=>p.product!=="outperformance"},
  {key:"finalLevel",type:"range",label:"Both paths finish at",min:75,max:135,step:1,format:v=>v.toFixed(0)},
  {key:"tenor",type:"range",label:"Tenor",min:.5,max:3,step:.5,format:v=>v.toFixed(1)+" years"},
  {key:"vol",type:"range",label:"Illustrative volatility",min:10,max:60,step:1,format:v=>v.toFixed(0)+"% p.a."},
  {key:"dividend",type:"range",label:"Forgone dividend yield",min:0,max:8,step:.25,format:v=>v.toFixed(2)+"% p.a."},
  {key:"fee",type:"range",label:"Fees and structuring margin",min:0,max:4,step:.25,format:v=>v.toFixed(2)+" points"}
];
const state={params:{...defaults}};
function svgEl(name,attrs={},text=""){const node=document.createElementNS("http://www.w3.org/2000/svg",name);Object.entries(attrs).forEach(([key,value])=>node.setAttribute(key,value));if(text)node.textContent=text;return node}
function signed(value,digits=0){return (value>0?"+":value<0?"−":"")+Math.abs(value).toFixed(digits)}
function renderControls(){const host=$("participation-controls");host.innerHTML="";controls.forEach(control=>{const block=document.createElement("div");block.className="control-block";block.dataset.control=control.key;block.hidden=control.show?!control.show(state.params):false;if(control.type==="range"){const label=document.createElement("label");label.className="range-control";label.htmlFor=`participation-${control.key}`;const head=document.createElement("span"),name=document.createElement("b"),output=document.createElement("output");name.textContent=control.label;output.id=`participation-output-${control.key}`;head.append(name,output);const input=document.createElement("input");input.type="range";input.id=`participation-${control.key}`;input.min=control.min;input.max=control.max;input.step=control.step;input.value=state.params[control.key];input.addEventListener("input",()=>{state.params[control.key]=Number(input.value);updateOutputs();scheduleRender()});label.append(head,input);block.append(label)}else{const title=document.createElement("span");title.className="control-title";title.textContent=control.label;const set=document.createElement("div");set.className="radio-set";control.options.forEach(([value,label])=>{const button=document.createElement("button");button.type="button";button.textContent=label;const on=state.params[control.key]===value;button.classList.toggle("on",on);button.setAttribute("aria-pressed",String(on));button.addEventListener("click",()=>{if(state.params[control.key]===value)return;state.params[control.key]=value;if(control.key==="product")Object.assign(state.params,presets[value]);renderControls();renderAll()});set.append(button)});block.append(title,set)}host.append(block)});updateOutputs()}
function updateOutputs(){controls.filter(control=>control.type==="range").forEach(control=>{const output=$(`participation-output-${control.key}`);if(output)output.textContent=control.format(state.params[control.key])})}
function productCopy(){const map={outperformance:["Outperformance · 1310",`Below 100 the product moves one-for-one with the underlying. Above 100 it participates at ${(state.params.participation*100).toFixed(0)}%, with no barrier or floor.`],bonus:["Bonus · 1320",`If the ${state.params.barrier} barrier survives, redemption is at least ${state.params.bonus}. A breach permanently converts the product into a tracker.`],bonus_outperformance:["Bonus Outperformance · 1330",`If the ${state.params.barrier} barrier survives, redemption is at least ${state.params.bonus}. A breach removes the floor but leaves ${(state.params.participation*100).toFixed(0)}% participation above 100 intact.`]};const [name,description]=map[state.params.product];$("participation-name").textContent=name;$("participation-description").textContent=description}
function pathD(path,X,Y){let d="";const step=Math.max(1,Math.floor(path.length/420));for(let day=0;day<path.length;day+=step)d+=(d?"L":"M")+X(day).toFixed(1)+","+Y(path[day]).toFixed(1);if((path.length-1)%step)d+="L"+X(path.length-1).toFixed(1)+","+Y(path.at(-1)).toFixed(1);return d}
function drawPaths(result){const svg=$("paired-path-chart");svg.innerHTML="";const end=result.paths.safe.length-1,values=[...result.paths.safe,...result.paths.touch,...(ParticipationEngine.hasBonus(state.params)?[state.params.barrier]:[])],min=Math.max(0,Math.min(...values)-8),max=Math.max(...values)+8,m={l:55,r:125,t:22,b:42},w=900,h=350,X=day=>m.l+day/end*(w-m.l-m.r),Y=value=>m.t+(max-value)/(max-min)*(h-m.t-m.b);for(let i=0;i<=4;i++){const value=min+(max-min)*i/4,y=Y(value);svg.append(svgEl("line",{x1:m.l,x2:w-m.r,y1:y,y2:y,class:"grid"}),svgEl("text",{x:m.l-8,y:y+3,"text-anchor":"end",class:"axis"},value.toFixed(0)))}[0,.5,1].forEach(fraction=>{const x=X(end*fraction);svg.append(svgEl("text",{x,y:h-14,"text-anchor":"middle",class:"axis"},fraction===0?"Start":fraction===1?"Maturity":"Mid-life"))});if(ParticipationEngine.hasBonus(state.params)){const y=Y(state.params.barrier);svg.append(svgEl("line",{x1:m.l,x2:w-m.r,y1:y,y2:y,stroke:colors.brick,"stroke-width":1.2,"stroke-dasharray":"5 4"}),svgEl("text",{x:w-m.r+7,y:y+3,fill:colors.brick,class:"level-label"},`barrier ${state.params.barrier}`))}svg.append(svgEl("path",{d:pathD(result.paths.safe,X,Y),class:"participation-safe"}),svgEl("path",{d:pathD(result.paths.touch,X,Y),class:"participation-touch"}));if(result.touch.day!==null)svg.append(svgEl("circle",{cx:X(result.touch.day),cy:Y(result.paths.touch[result.touch.day]),r:5,fill:colors.brick,class:"event-dot"}));const finalY=Y(result.final);svg.append(svgEl("circle",{cx:X(end),cy:finalY,r:4,fill:colors.ink}),svgEl("text",{x:w-m.r+7,y:finalY+3,fill:colors.ink,class:"direct-label"},`both finish ${result.final.toFixed(0)}`));svg.setAttribute("aria-label",`Two paths finish at ${result.final.toFixed(0)}. The first barrier state is ${result.safe.breached?"breached":"intact"} and redemption is ${result.safe.redemption.toFixed(1)}. The second state is ${result.touch.breached?"breached":"intact"} and redemption is ${result.touch.redemption.toFixed(1)}.`)}
function renderOutcomes(result){const host=$("paired-outcomes");host.innerHTML="";[["Path A · avoids the dip",result.safe],["Path B · touches and recovers",result.touch]].forEach(([label,outcome])=>{const item=document.createElement("div"),status=document.createElement("span"),value=document.createElement("strong"),detail=document.createElement("p");status.textContent=ParticipationEngine.hasBonus(state.params)?outcome.breached?"Barrier breached":"Barrier intact":"No barrier";value.textContent=outcome.redemption.toFixed(1);detail.textContent=`${label} · ${signed(outcome.redemption-100,1)}% product return`;item.className=outcome.breached?"path-outcome breached":"path-outcome intact";item.append(status,value,detail);host.append(item)})}
function payoffPath(values,X,Y){return values.map((point,index)=>(index?"L":"M")+X(point[0]).toFixed(1)+","+Y(point[1]).toFixed(1)).join("")}
function drawPayoff(){
  const svg=$("participation-payoff-chart");svg.innerHTML="";
  const lo=30,hi=175,series=[{values:[]},{values:[]},{values:[]}];
  for(let level=lo;level<=hi;level++){
    series[0].values.push([level,level]);
    series[1].values.push([level,ParticipationEngine.redemption(level,true,state.params)]);
    series[2].values.push([level,ParticipationEngine.redemption(level,false,state.params)]);
  }
  const max=Math.max(...series.flatMap(item=>item.values.map(point=>point[1])))+8,min=22,m={l:54,r:18,t:22,b:45},w=760,h=350;
  const X=value=>m.l+(value-lo)/(hi-lo)*(w-m.l-m.r),Y=value=>m.t+(max-value)/(max-min)*(h-m.t-m.b);
  for(let i=0;i<=4;i++){
    const value=min+(max-min)*i/4,y=Y(value);
    svg.append(svgEl("line",{x1:m.l,x2:w-m.r,y1:y,y2:y,class:"grid"}),svgEl("text",{x:m.l-8,y:y+3,"text-anchor":"end",class:"axis"},value.toFixed(0)));
  }
  [40,70,100,130,160].forEach(value=>{
    const x=X(value);
    svg.append(svgEl("line",{x1:x,x2:x,y1:m.t,y2:h-m.b,class:"grid"}),svgEl("text",{x,y:h-19,"text-anchor":"middle",class:"axis"},value.toFixed(0)));
  });
  svg.append(svgEl("path",{d:payoffPath(series[0].values,X,Y),class:"payoff-underlying"}));
  if(state.params.product==="outperformance")svg.append(svgEl("path",{d:payoffPath(series[1].values,X,Y),class:"payoff-outperformance"}));
  else svg.append(svgEl("path",{d:payoffPath(series[1].values,X,Y),class:"payoff-breached"}),svgEl("path",{d:payoffPath(series[2].values,X,Y),class:"payoff-intact"}));
  const strikeX=X(100);
  svg.append(svgEl("line",{x1:strikeX,x2:strikeX,y1:m.t,y2:h-m.b,stroke:colors.steel,"stroke-width":1.1,"stroke-dasharray":"4 4"}),svgEl("text",{x:strikeX+5,y:h-m.b-7,fill:colors.steel,class:"level-label"},"strike 100"));
  if(ParticipationEngine.hasBonus(state.params)){
    const cross=ParticipationEngine.crossover(state.params),crossX=X(cross);
    svg.append(svgEl("line",{x1:crossX,x2:crossX,y1:m.t,y2:h-m.b,stroke:colors.amber,"stroke-width":1,"stroke-dasharray":"3 4"}),svgEl("text",{x:crossX+5,y:m.t+13,fill:colors.amber,class:"level-label"},`floor hands over ${cross.toFixed(1)}`));
  }
  svg.append(svgEl("text",{x:(m.l+w-m.r)/2,y:h-2,"text-anchor":"middle",class:"axis"},"Underlying at maturity"),svgEl("text",{x:13,y:(m.t+h-m.b)/2,transform:`rotate(-90 13 ${(m.t+h-m.b)/2})`,"text-anchor":"middle",class:"axis"},"Redemption"));
  svg.setAttribute("aria-label",state.params.product==="outperformance"?`Outperformance payoff has one-for-one downside and ${(state.params.participation*100).toFixed(0)} percent upside participation above 100.`:`Barrier-intact redemption is at least ${state.params.bonus}; after breach the payoff follows the ${state.params.product==="bonus"?"underlying":"outperformance line"}.`);
  const legend=$("participation-payoff-legend");legend.innerHTML="";
  const entries=state.params.product==="outperformance"?[["underlying","Underlying"],["outperformance","Outperformance"]]:[["underlying","Underlying"],["breached",state.params.product==="bonus"?"After breach · tracker":"After breach · outperformance"],["intact","Barrier intact"]];
  entries.forEach(([key,label])=>{const item=document.createElement("span"),swatch=document.createElement("i");swatch.className=`legend-${key}`;item.append(swatch,document.createTextNode(label));legend.append(item)});
}
function renderBudget(){const result=ParticipationEngine.budget(state.params),host=$("budget-bar"),scale=Math.max(result.available,result.totalFeatureCost,.0001),upsideWidth=result.upsideCost/scale*100,protectionWidth=result.protectionCost/scale*100,unusedWidth=Math.max(0,result.available-result.totalFeatureCost)/scale*100;host.innerHTML="";[["budget-upside",upsideWidth],["budget-protection",protectionWidth],["budget-unused",unusedWidth]].forEach(([className,width])=>{if(width<=.01)return;const segment=document.createElement("span");segment.className=className;segment.style.width=`${width}%`;host.append(segment)});host.setAttribute("aria-label",`${result.available.toFixed(2)} points available; ${result.upsideCost.toFixed(2)} spent on extra upside and ${result.protectionCost.toFixed(2)} on the bonus floor.`);const remaining=result.available-result.totalFeatureCost,message=$("budget-message");message.textContent=remaining>=0?`The selected features use ${result.totalFeatureCost.toFixed(2)} of ${result.available.toFixed(2)} available points. ${remaining.toFixed(2)} remains unspent.`:`The selected features need ${(-remaining).toFixed(2)} points more than the dividend budget provides. Participation, bonus, barrier, fee or tenor must change.`;message.className=`budget-message ${remaining<0?"event-negative":""}`;const metrics=$("budget-metrics");metrics.innerHTML="";[["Available after fees",result.available],["Extra-upside cost",result.upsideCost],["Bonus-floor cost",result.protectionCost],["Budget used",Number.isFinite(result.budgetUse)?result.budgetUse*100:Infinity]].forEach(([label,value],index)=>{const item=document.createElement("div"),span=document.createElement("span"),strong=document.createElement("strong");span.textContent=label;strong.textContent=index===3?(Number.isFinite(value)?value.toFixed(0)+"%":"Unfunded"):value.toFixed(2);item.append(span,strong);metrics.append(item)});const method=state.params.monitoring==="daily"?"Daily-monitored barrier":"Maturity-only barrier";$("budget-method").textContent=`Foregone-dividend value ${(100-result.zeroCall).toFixed(2)} − fees ${state.params.fee.toFixed(2)} = ${result.available.toFixed(2)} available. ${ParticipationEngine.hasBonus(state.params)?`${method} cost uses a ${result.steps}-step tree.`:"Extra participation uses a closed-form call illustration."}`}
function drawHistogram(returns){const svg=$("participation-histogram");svg.innerHTML="";const bins=38,lo=returns[0],hi=returns.at(-1),span=Math.max(1,hi-lo),counts=new Array(bins).fill(0);returns.forEach(value=>counts[Math.min(bins-1,Math.floor((value-lo)/span*bins))]++);const max=Math.max(...counts),m={l:55,r:20,t:18,b:40},w=900,h=210,X=value=>m.l+(value-lo)/span*(w-m.l-m.r),Y=count=>m.t+(max-count)/max*(h-m.t-m.b),barW=(w-m.l-m.r)/bins;[0,.5,1].forEach(fraction=>{const y=Y(max*fraction);svg.append(svgEl("line",{x1:m.l,x2:w-m.r,y1:y,y2:y,class:"grid"}))});counts.forEach((count,index)=>{const midpoint=lo+(index+.5)/bins*span;svg.append(svgEl("rect",{x:m.l+index*barW+.7,y:Y(count),width:Math.max(1,barW-1.4),height:h-m.b-Y(count),fill:midpoint<0?colors.brick:colors.jade,opacity:.72}))});if(lo<0&&hi>0)svg.append(svgEl("line",{x1:X(0),x2:X(0),y1:m.t,y2:h-m.b,stroke:colors.ink,"stroke-width":1.3}));for(let i=0;i<=4;i++){const value=lo+span*i/4,x=X(value);svg.append(svgEl("text",{x,y:h-17,"text-anchor":"middle",class:"axis"},signed(value,0)+"%"))}svg.append(svgEl("text",{x:(m.l+w-m.r)/2,y:h-2,"text-anchor":"middle",class:"axis"},"Product return at maturity"))}
function renderRules(){const hasBonus=ParticipationEngine.hasBonus(state.params),factor=(ParticipationEngine.participation(state.params)*100).toFixed(0),rows=[];if(hasBonus)rows.push(["Observe barrier",state.params.monitoring==="daily"?`Any daily close at or below ${state.params.barrier}`:`Final level at or below ${state.params.barrier}`,"Store barrier-breached state permanently"]);if(state.params.product==="outperformance")rows.push(["Downside",`Final level at or below 100`,"Redeem one-for-one with the underlying"],["Upside",`Final level above 100`,`Redeem 100 + ${factor}% × (final − 100)`]);else{rows.push(["Barrier intact","No barrier event",`Redeem the greater of ${state.params.bonus} and the ${state.params.product==="bonus"?"underlying":"outperformance"} line`]);rows.push(["Barrier breached","Barrier event stored",state.params.product==="bonus"?"Redeem as a tracker":"Redeem as an outperformance certificate"]);rows.push(["Floor crossover",`Final level below ${ParticipationEngine.crossover(state.params).toFixed(1)}`,`The intact-state bonus floor ${state.params.bonus} determines redemption`])}rows.push(["Settlement","Final branch is one-for-one below strike","Physical delivery may replace the equivalent cash amount"]);const body=$("participation-rules-body");body.innerHTML="";rows.forEach(values=>{const row=document.createElement("tr");values.forEach(value=>{const cell=document.createElement("td");cell.textContent=value;row.append(cell)});body.append(row)});const strip=$("participation-rule-strip"),steps=hasBonus?["Observe barrier","Store state","Fix final level","Apply state formula","Settle"]:["Fix final level","Test strike","Apply participation","Settle"];strip.innerHTML="<b>Evaluation order</b>";steps.forEach(step=>{const arrow=document.createElement("i"),span=document.createElement("span");arrow.textContent="→";span.textContent=step;strip.append(arrow,span)})}
let simulationTimer,simulationVersion=0,worker=null,workerBusy=false,pendingPayload=null;
function renderSimulation(message){if(message.id!==simulationVersion)return;const returns=Array.from(message.returns),q=index=>returns[Math.max(0,Math.min(returns.length-1,Math.floor(index*(returns.length-1))))],definitions=state.params.product==="outperformance"?[["Final above strike",message.stats.leveraged],["Average return",message.stats.averageReturn/100],["5th percentile",q(.05)/100],["95th percentile",q(.95)/100]]:[["Barrier breached",message.stats.breached],["Bonus floor sets payoff",message.stats.floor],[state.params.product==="bonus"?"Underlying sets payoff":"Outperformance sets payoff",message.stats.leveraged],["Average return",message.stats.averageReturn/100]],host=$("participation-stats");host.innerHTML="";definitions.forEach(([label,value],index)=>{const item=document.createElement("div"),span=document.createElement("span"),strong=document.createElement("strong");item.className="stat";span.textContent=label;strong.textContent=index===3&&state.params.product!=="outperformance"?signed(value*100,1)+"%":index>0&&state.params.product==="outperformance"?signed(value*100,1)+"%":Math.round(value*100)+"%";item.append(span,strong);host.append(item)});drawHistogram(returns);$("participation-simulation-status").textContent=`Current · ${message.count.toLocaleString()} paths · ${state.params.tenor.toFixed(1)} years · ${state.params.vol.toFixed(0)}% volatility · zero drift`}
function postSimulation(payload){if(typeof Worker==="undefined"){setTimeout(()=>renderSimulation({id:payload.id,...ParticipationEngine.simulate(payload.params,payload.seed,payload.count)}),0);return}if(!worker){worker=new Worker("participation-worker.js?v=1");worker.onmessage=event=>{workerBusy=false;renderSimulation(event.data);if(pendingPayload){const next=pendingPayload;pendingPayload=null;postSimulation(next)}}}if(workerBusy){pendingPayload=payload;return}workerBusy=true;worker.postMessage(payload)}
function scheduleSimulation(){const id=++simulationVersion;clearTimeout(simulationTimer);$("participation-simulation-status").textContent="Updating simulated outcomes…";simulationTimer=setTimeout(()=>postSimulation({id,params:{...state.params},seed:774913,count:2000}),140)}
function renderAll(){productCopy();updateOutputs();const result=ParticipationEngine.pairOutcomes(state.params);drawPaths(result);renderOutcomes(result);drawPayoff();renderBudget();renderRules();scheduleSimulation()}
let renderFrame=0;function scheduleRender(){cancelAnimationFrame(renderFrame);renderFrame=requestAnimationFrame(renderAll)}
$("reset").addEventListener("click",()=>{state.params={...defaults};renderControls();renderAll()});renderControls();renderAll();
